### PR TITLE
Update SugarModules/modules/Asterisk/include/AsteriskJS.php

### PR DESCRIPTION
**Pull request by chsergey**
$user_extension may be "Not configured" - Illegal Input
$current_user_id is hash-like string and for js is Illegal Input

we need '$var'

### CODE REVIEW

**Comment by askhogan** [comment]
Please provide a few examples of user IDs that get this error.

**Comment by chsergey** [comment]
for example 
1. <script type="text/javascript">window.yaai_poll_rate = 5000;</script>
2. <script type="text/javascript">window.yaai_user_extension = 10002;</script>
3. <script type="text/javascript">window.yaai_current_user_id = 9261efd9-1cbf-b6fe-37f3-50b5ee263bf5;</script>

on line 3 I've error "SyntaxError: Unexpected token ILLEGAL"

**Comment by chsergey** [comment]
I think we need modify output of line 3 to 
window.yaai_current_user_id = '9261efd9-1cbf-b6fe-37f3-50b5ee263bf5';

**Comment by askhogan** [comment]
I see your point... I just don't get the syntax.  There is already a ''
here... The edits look like a change to '"' '"' it just seems confusing.
Let me take a look.

**Comment by chsergey** [comment]
There is already a '' in php context, but after echo there is no have '' in javascript context.

**Pull request merged**
