### PR TITLE
Update SugarModules/modules/Asterisk/include/controller.php

### PR DESCRIPTION
**Pull request by superles**

### CODE REVIEW

**Comment by blak3r** [comment]
Hi Superles,

That's interesting.  That means there must be a bug in "restructureChatBoxes".  There is no reason for the chatboxid to be set but the callRecordId to not be set otherwise.

Do you know exactly how to reproduce the bug?  I just tried making three outbound calls then tried closing them.  I was able to close each one of them and the call windows never disappeared.  (Note: I didn't incorporate your fix yet.)

I want to hopefully fix the source of the problem.

```
  function closeChatBox(chatboxid) {
    if( !isChatBoxClosed(chatboxid) ) {
        $('#chatbox_'+chatboxid).css('display','none');
        restructureChatBoxes();

        callRecordId = getChatCallRecordId( chatboxid );

        if( callRecordId == null ) {
            alert("Call popup notification logic error.  Please refresh page to close boxes.")
        }
        else {
            // Tells asterisk_log table that user has closed this entry.
            $.post("index.php?entryPoint=AsteriskController&action=updateUIState", {id: chatboxid, ui_state: "Closed", call_record: callRecordId} );
        }
    }
  }
```

**Comment by blak3r** [comment]
@superles Can you update this thread with a recipe for reproducing this bug so we can better track down the source of this bug?

**Comment by superles** [comment]
I'm sorry. I was away. I will join 01.06.2012. I agree that your solution is more elegant. So I'm going to close your request, and you make your changes to the code. I'll come and help in the tests.

**Comment by blak3r** [comment]
@superles Has this issue definitely gone away?  My fix above wasn't really a fix as much as a detector of the issue.  Since we emailed back and forth on this topic I haven't really seen the problem come up.

**Comment by blak3r** [comment]
As discovered by @miksir on: https://github.com/blak3r/yaai/issues/45
The problem manifests itself on pages with are loaded with AJAX.

The problem should be fixed in dialin.js,  for some reason the array which I store the callRecordIds in is returning null on pages with AJAX on them.  No idea why.  But, fortunately the callRecordId is the chatboxId which is passed in to the various methods where that info is needed so we don't have to rely on that array.  It'd be neat to figure out why this is but for now I don't have the time to investigate further.

**Comment by askhogan** [comment]
Hmmm.  That sounds really weird.  I think I am going to require call_record_id in the updated code in my fork.  I can't see why this would be the way.  It is possible that there was some issue with having the variables global???  I don't know.  In my code all variables are all encapsulated in the YAAI object so they should be safe.  

I also noticed that in the transfer method there is no workaround that queries AsteriskID and is totally dependent on the passed call_record_id.  So I assume if the transfer is working this issue must be old??

**Pull request merged**
